name: Project-Automation-GITHUB
description: test random description
version: 0.0.1
author: abhisheks+e2etests@prophecy.io
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: projectautomationgithub
  parentArtefactID: abhishekse2etestsprophecyioteam
  buildSystem: maven
  author: null
  createdAt: '2025-05-20 06:05:17'
pipelines:
  pipelines/Workflow-Automation-GITHUB-1747720901364:
    name: Workflow-Automation-GITHUB-1747720901364
    description: automation workflow
    author: abhisheks+e2etests@prophecy.io
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2025-05-20 06:05:17'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.1.26
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-05-20 06:05:17'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-05-20T06:05:17.97072Z'
  name: plibMaven
  version: 8.9.0
  id: '452847017'
  createdAt: '2025-05-20T06:05:17.97072Z'
  type: plibMaven
projectDependencies:
  '12652':
    projectUID: 12652
    projectName: ProphecyWarehouseScala
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12652.git&subPath=
    version: 0.0.6
    isDefault: true
    author: null
    createdAt: '2025-05-20 06:02:49'
  '12651':
    projectUID: 12651
    projectName: ProphecySparkBasicsScala
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12651.git&subPath=
    version: 0.2.6.2
    isDefault: true
    author: null
    createdAt: '2025-05-20 06:02:49'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
