name: Project-Automation-GITHUB
description: test random description
version: 0.0.1
author: abhisheks+e2etests@prophecy.io
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: projectautomationgithub
  parentArtefactID: abhishekse2etestsprophecyioteam
  buildSystem: maven
  author: null
  createdAt: '2025-08-03 00:28:11'
pipelines:
  pipelines/Workflow-Automation-GITHUB-1754180662871:
    name: Workflow-Automation-GITHUB-1754180662871
    description: automation workflow
    author: abhisheks+e2etests@prophecy.io
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2025-08-03 00:28:11'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.1.26
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-08-03 00:28:11'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-08-03T00:28:11.955213Z'
  name: plibMaven
  version: 8.12.0-SNAPSHOT
  id: '1632346488'
  createdAt: '2025-08-03T00:28:11.955213Z'
  type: plibMaven
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: false
pipelineConfigurations: {}
projectConfigurations: {}
